// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("kafka-net")]
[assembly: AssemblyDescriptionAttribute("Native C# client for Apache Kafka.")]
[assembly: GuidAttribute("eb234ec0-d838-4abd-9224-479ca06f969d")]
[assembly: AssemblyProductAttribute("kafka-net")]
[assembly: AssemblyCompanyAttribute("James Roland")]
[assembly: AssemblyCopyrightAttribute("Copyright James Roland 2014")]
[assembly: AssemblyVersionAttribute("0.8.0.23")]
[assembly: AssemblyFileVersionAttribute("0.8.0.23")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.8.0.23";
    }
}
